"""
iCalendar (.ics) Generator
Converts daily learning schedule JSON into a valid iCalendar string
that can be imported into Google Calendar or Apple Calendar.
"""
from datetime import datetime, date, timedelta
import uuid
import re


def _sanitize(text: str) -> str:
    """Escape special characters for iCalendar format."""
    if not text:
        return ""
    text = str(text)
    text = text.replace("\\", "\\\\")
    text = text.replace(";", "\\;")
    text = text.replace(",", "\\,")
    text = text.replace("\n", "\\n")
    return text


def _fold_line(line: str) -> str:
    """Fold long iCalendar lines at 75 octets per RFC 5545."""
    result = []
    while len(line.encode("utf-8")) > 75:
        # Find safe split point within 75 bytes
        chunk = line[:75]
        while len(chunk.encode("utf-8")) > 75:
            chunk = chunk[:-1]
        result.append(chunk)
        line = " " + line[len(chunk):]
    result.append(line)
    return "\r\n".join(result)


def _format_dt(dt_str: str, time_hour: int = 8) -> str:
    """Convert ISO date string to iCalendar datetime format."""
    try:
        d = date.fromisoformat(dt_str)
        dt = datetime(d.year, d.month, d.day, time_hour, 0, 0)
        return dt.strftime("%Y%m%dT%H%M%S")
    except Exception:
        today = datetime.now()
        return today.strftime("%Y%m%dT%H%M%S")


def generate_ics(
    schedule_data: dict,
    calendar_name: str = "NoteMind Learning Roadmap",
    start_hour: int = 8,
) -> str:
    """
    Generate an iCalendar (.ics) string from a daily learning schedule.

    Args:
        schedule_data: The schedule dict from SchedulerAgent with 'schedule' list
        calendar_name: Display name for the calendar
        start_hour: Hour of day to schedule events (default 8 = 8 AM)

    Returns:
        Valid iCalendar string
    """
    now_str = datetime.utcnow().strftime("%Y%m%dT%H%M%SZ")
    lines = [
        "BEGIN:VCALENDAR",
        "VERSION:2.0",
        f"PRODID:-//NoteMind//Learning Roadmap//VI",
        "CALSCALE:GREGORIAN",
        "METHOD:PUBLISH",
        f"X-WR-CALNAME:{_sanitize(calendar_name)}",
        "X-WR-TIMEZONE:Asia/Ho_Chi_Minh",
        "X-WR-CALDESC:Generated by NoteMind AI Learning Roadmap",
    ]

    schedule = schedule_data.get("schedule", [])

    for day_entry in schedule:
        day_num = day_entry.get("day", 1)
        date_str = day_entry.get("date", "")
        milestone_title = day_entry.get("milestone_title", "")
        day_title = day_entry.get("title", f"Day {day_num}")
        day_summary = day_entry.get("day_summary", "")
        total_hours = day_entry.get("total_hours", 2.0)
        activities = day_entry.get("activities", [])

        # Build description
        desc_parts = []
        if day_summary:
            desc_parts.append(f"📋 {day_summary}")
        desc_parts.append(f"🎯 Milestone: {milestone_title}")
        desc_parts.append("")
        for act in activities:
            act_type = act.get("type", "theory").upper()
            topic = act.get("topic", act.get("description", ""))
            mins = act.get("duration_minutes", 60)
            desc_parts.append(f"• [{act_type}] {topic} ({mins} phút)")

        description = _sanitize("\\n".join(desc_parts))
        summary = _sanitize(f"📚 Ngày {day_num}: {day_title}")

        # Calculate times
        dtstart = _format_dt(date_str, start_hour)
        duration_mins = int(total_hours * 60)
        try:
            d = date.fromisoformat(date_str)
            end_dt = datetime(d.year, d.month, d.day, start_hour, 0, 0) + timedelta(minutes=duration_mins)
            dtend = end_dt.strftime("%Y%m%dT%H%M%S")
        except Exception:
            dtend = _format_dt(date_str, start_hour + 2)

        event_uid = str(uuid.uuid4())

        lines.extend([
            "BEGIN:VEVENT",
            f"UID:{event_uid}",
            f"DTSTAMP:{now_str}",
            f"DTSTART:{dtstart}",
            f"DTEND:{dtend}",
            f"SUMMARY:{summary}",
            f"DESCRIPTION:{description}",
            f"CATEGORIES:Education,NoteMind",
            f"STATUS:CONFIRMED",
            f"TRANSP:OPAQUE",
            "END:VEVENT",
        ])

    lines.append("END:VCALENDAR")

    # Join with CRLF as per RFC 5545
    ics_content = "\r\n".join(lines) + "\r\n"
    return ics_content


def generate_ics_from_state(state: dict) -> str:
    """
    Convenience wrapper — extract schedule from NotebookState and generate ICS.
    """
    schedule_data = state.get("daily_schedule") or {}
    learner_profile = state.get("learner_profile") or {}
    notebook_id = state.get("notebook_id", "")

    calendar_name = f"NoteMind — {learner_profile.get('goal', 'Learning Roadmap')}"
    return generate_ics(schedule_data, calendar_name=calendar_name)
